### ISSUE TITLE
Make the CommandTree public

### ISSUE THREAD

**Issue by Nikey646** [Nihlus/Remora.Commands#1]
It should be possible to view the constructed CommandTree from the CommandService to be able to dynamically generate a help command and review the command structure.

If you think the CommandTree would be too complex to use to generate a help command, it might be an idea to provide a simplified overview of the available commands from the CommandService.

Edit: Yay, first issue!

**Comment by Nihlus** [comment]
This is a good use case, and I've changed the access modifiers to the relevant types. It may be worth breaking out some of the more general functionality into another helper library, though.
