### ISSUE TITLE
Bogus service registrations for CommandGroup classes.

### ISSUE THREAD

**Issue by JakenVeina** [Nihlus/Remora.Commands#4]
**Description**

The `ServiceCollectionExtensions.AddCommandGroup<T>()` method registers `T` as a simple transient service, despite the fact that the IoC container is Not responsible for constructing instances of `T`. This results in service provider validation errors when the `additionalParameters` functionality of `CommandService.TryExecuteAsync()` is utilized, as the IoC container sees these additional parameters in the constructor as dependencies that it must resolve.

By my reckoning, the only place `CommandGroup` classes are constructed is [here](https://github.com/Nihlus/Remora.Commands/blob/399f6ad6cbd60a508abc87c17d2b470de80a2c64/Remora.Commands/Services/CommandService.cs#L541), which does not require the constructed class to be registered within the IoC container at all. Only its other dependencies must be registered.

The easy solution here is to just remove the bogus registration [here](https://github.com/Nihlus/Remora.Commands/blob/399f6ad6cbd60a508abc87c17d2b470de80a2c64/Remora.Commands/Extensions/ServiceCollectionExtensions.cs#L55) however I would recommend considering, in the future, reworking this system to allow the construction of `CommandGroup` classes to be handled by the IoC, allowing for a more correct, validatable dependency tree. In this case, an `ICommandContext` could be injected into commands in several ways. The context could be injected through an `internal init` property upon `CommandGroup`. It could also be injected through an `ICommandContextAccessor` interface that is registered with the IoC container normally, and which `CommandService` populates before executing each command.

**Steps to Reproduce**

Run the [DiceRoller](https://github.com/Nihlus/Remora.Discord/tree/master/Samples/DiceRoller) sample application with service provider validation enabled.

**Expected Behavior**

The recommended usage pattern of the commands system should not produce an invalid service collection.

**Current Behavior**

The registration of `DiceRollCommands` to the IoC container constitutes an invalid service registration, as there are no service registrations for `ICommandContext`, nor could there be, as the data required to populate the interface is unavailable during service construction.

**Library / Runtime Information**

Using Visual Studio Community 2019, upon commit 57712e7b of Remora.Discord (referencing version 1.3.0 of Remora.Commands).

**Comment by Nihlus** [comment]
I'm unable to reproduce this after merging the changes in Remora.Discord - could you verify that this is indeed the issue?

**Comment by Nihlus** [comment]
Reproduction aside, the reasoning is sound, and there's no need to have the group registered in the DI container. We can do another pass at this in the future, should the need arise.

**Comment by JakenVeina** [comment]
Yup. It's good on my end now.
